version: '2.4'
services:
  influxdb:
    image: influxdb:1.8.10-alpine
    ports:
      - "8086:8086"
    networks:
      - monitoring-network
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - ./mnt/docker/influx_init.iql:/docker-entrypoint-initdb.d/influx_init.iql
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:8.5.2
    depends_on:
      - influxdb
      - prometheus
    volumes:
      - ./mnt/docker/grafana/provisioning/:/etc/grafana/provisioning/
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    env_file:
      - 'grafana.env'
    links:
      - influxdb
      - prometheus
    networks:
      - monitoring-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./mnt/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    networks:
      - monitoring-network

volumes:
  prometheus_data: { }
  grafana_data: {}
  influxdb_data: {}

networks:
  monitoring-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
