version: "2.4"
services:
  influxdb:
    build:
      context: ./influxdb
      dockerfile: Dockerfile
    image: influxdb/v1.8
    container_name: influxdb-monitoring
    ports:
      - "8086:8086"
    networks:
      - monitoring-network
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    image: grafana
    container_name: grafana-monitoring
    depends_on:
      - influxdb
      # - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    env_file:
      - "grafana.env"
    links:
      - influxdb
      - prometheus
    networks:
      - monitoring-network

  # prometheus:
  #   build:
  #     context: ./prometheus
  #     dockerfile: Dockerfile
  #   image: prometheus
  #   container_name: prometheus-monitoring
  #   restart: unless-stopped
  #   volumes:
  #     - prometheus_data:/prometheus
  #   expose:
  #     - 9090
  #   networks:
  #     - monitoring-network

  # zipkin:
  #   image: ghcr.io/openzipkin/zipkin-slim
  #   container_name: zipkin
  #   ports:
  #     - 9411:9411
  #   networks:
  #     - monitoring-network

volumes:
  prometheus_data: {}
  grafana_data: {}
  influxdb_data: {}

networks:
  monitoring-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
