version: "2.4"
services:
  influxdb:
    build:
      context: ./influxdb
      args:
        INFLUXDB_USERNAME: ${INFLUXDB_USERNAME}
        INFLUXDB_PASSWORD: ${INFLUXDB_PASSWORD}
        INFLUXDB_ORG: ${INFLUXDB_ORG}
        INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
        INFLUXDB_ADMIN_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
      dockerfile: Dockerfile
    image: influxdb/v2
    container_name: influxdb-monitoring
    ports:
      - "8086:8086"
    networks:
      - monitoring-network
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    build:
      context: ./grafana
      args:
        GF_SECURITY_ADMIN_USER: ${GRAFANA_USERNAME}
        GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
        INFLUXDB_ORG: ${INFLUXDB_ORG}
        INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
        INFLUXDB_ADMIN_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
      dockerfile: Dockerfile
    image: grafana
    container_name: grafana-monitoring
    depends_on:
      - influxdb
      # - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    links:
      - influxdb
      # - prometheus
    networks:
      - monitoring-network

volumes:
  grafana_data: {}
  influxdb_data: {}

networks:
  monitoring-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
