version: '2.4'
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    build: ./influxdb
    ports:
      - "8086:8086"
    networks:
      - monitoring-network
    volumes:
      - influxdb_data:/var/lib/influxdb2

  grafana:
    image: grafana
    container_name: grafana
    build: ./grafana
    depends_on:
      - influxdb
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    env_file:
      - 'grafana.env'
    links:
      - influxdb
      - prometheus
    networks:
      - monitoring-network

  prometheus:
    image: prometheus
    container_name: prometheus
    restart: unless-stopped
    build: ./prometheus
    volumes:
      - prometheus_data:/prometheus
    expose:
      - 9090
    networks:
      - monitoring-network

  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - monitoring-network

volumes:
  prometheus_data: { }
  grafana_data: { }
  influxdb_data: { }

networks:
  monitoring-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
