version: '2.4'
services:
  influxdb:
    image: influxdb:1.8.10-alpine
    ports:
     - "8086:8086"
     - 25826:25826/udp
    networks:
     - grafana-influxdb-network
    volumes:
     - ./influxdb/influx_init.iql:/docker-entrypoint-initdb.d/influx_init.iql
     - ./influxdb/types.db:/usr/share/collectd/types.db:ro
     - ./influxdb/data:/var/lib/influxdb
     - ./influxdb/:/etc/influxdb/

  grafana:
    image: grafana/grafana:8.5.2
    depends_on:
      - influxdb
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
    env_file:
      - 'grafana.env'
    links:
      - influxdb
    networks:
      - grafana-influxdb-network

networks:
  grafana-influxdb-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
