apiVersion: 1

datasources:
  - name: InfluxDB
    version: 2
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      defaultBucket: $DOCKER_INFLUXDB_INIT_BUCKET
      httpMode: POST
      organization: $DOCKER_INFLUXDB_INIT_ORG
      version: Flux
    secureJsonData:
      token: $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true
