version: '3.7'

services:
  grafana:
    build: './config/grafana'
    ports:
      - 3000:3000
    user: "$UID:$GID"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    user: "$UID:$GID"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      monitoring:
        aliases:
          - prometheus
  influxDB:
    image: influxdb:2.6.1
    ports:
      - 8086:8086
    user: "$UID:$GID"
networks:
  monitoring: